version: '3.3'

services: 
    # app:
    #     image: backend:latest
    #     build:
    #         context: ./backend
    #     ports:
    #         - "8000:8000"
    #     volumes:
    #         - ./backend:/app/backend/
        #env_file:
            #- ./docker/docker.app.env
    tf-serving:
        image: tensorflow-serving:latest
        ports:
          - "8500:8500"
          - "8501:8501"
        network_mode: "host"
        
