# Generated by Django 4.0.2 on 2022-02-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1, verbose_name='Version')),
            ],
        ),
        migrations.CreateModel(
            name='Tfmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('base_path', models.CharField(max_length=50, verbose_name='Path')),
                ('model_platform', models.CharField(choices=[('tensorflow', 'tensorflow'), ('other', 'other')], max_length=20, verbose_name='Platform')),
                ('version', models.ManyToManyField(related_name='model_version', to='core.Version', verbose_name='Version')),
            ],
        ),
    ]
